name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v3.0.0
        with:
          github_user_name: Mizoo1
          outputs: dist/snake.svg

      - name: Push Snake to the output branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: output
          force: true
          directory: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
